# Generated by Django 3.1.2 on 2020-12-13 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_auto_20201125_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(default='', max_length=16, verbose_name='Numero de tarjeta')),
                ('due_date', models.CharField(default='', max_length=5, verbose_name='Fecha de vencimiento')),
                ('ccv', models.CharField(default='', max_length=3, verbose_name='CCV')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='creditcard',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.creditcards'),
        ),
    ]
