# Generated by Django 3.1.2 on 2020-12-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_auto_20201212_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creditcard',
        ),
    ]
