# Generated by Django 3.1.2 on 2020-12-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_remove_user_creditcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCards',
        ),
    ]
