# Generated by Django 3.1.2 on 2020-12-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_delete_creditcards'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.CharField(default='', max_length=16, verbose_name='Numero de tarjeta')),
                ('due_date', models.CharField(default='', max_length=5, verbose_name='Fecha de vencimiento')),
                ('ccv', models.CharField(default='', max_length=3, verbose_name='CCV')),
            ],
        ),
    ]
