# Generated by Django 3.1.2 on 2020-12-13 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_creditcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creditcard',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Usuarios.creditcards'),
        ),
    ]
