# Generated by Django 3.1.2 on 2020-12-13 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0012_user_creditcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creditcard',
        ),
        migrations.AddField(
            model_name='creditcards',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
