# Generated by Django 3.1.2 on 2020-12-13 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0014_auto_20201212_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcards',
            name='año_de_vencimiento',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='creditcards',
            name='ccv',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(111)]),
        ),
    ]
