# Generated by Django 3.1.2 on 2020-11-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0007_auto_20201125_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='tlf',
            new_name='telefono',
        ),
    ]
