# Generated by Django 3.1.2 on 2020-11-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0009_auto_20201125_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='clave',
            field=models.CharField(default='PasssW0rd', max_length=30),
            preserve_default=False,
        ),
    ]
