# Generated by Django 3.1.2 on 2020-12-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0010_clientes_clave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
