# Generated by Django 3.1.2 on 2020-12-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0011_delete_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
