# Generated by Django 3.1.2 on 2020-12-12 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionVenta', '0012_delete_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=10, unique=True, verbose_name='Referencia')),
                ('products', models.CharField(default='', max_length=250, verbose_name='Productos')),
                ('units', models.CharField(default='', max_length=250, verbose_name='Unidades')),
                ('seller', models.CharField(default='', max_length=10, verbose_name='Vendedor')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
            ],
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fact',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='gestionVenta.facturas'),
        ),
    ]
