# Generated by Django 3.1.2 on 2020-12-12 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0013_auto_20201211_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 11, 23, 59, 34, 55167), verbose_name='Fecha'),
        ),
    ]
