# Generated by Django 3.1.2 on 2020-12-12 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0014_auto_20201211_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 0, 20, 47, 411325), verbose_name='Fecha'),
        ),
    ]
