# Generated by Django 3.1.2 on 2020-12-12 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0016_auto_20201212_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 0, 41, 35, 138521), verbose_name='Fecha'),
        ),
    ]
