# Generated by Django 3.1.2 on 2020-12-12 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0017_auto_20201212_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Numero de Productos'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 1, 42, 26, 199649), verbose_name='Fecha'),
        ),
    ]
