# Generated by Django 3.1.2 on 2020-12-12 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0018_auto_20201212_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='prices',
            field=models.CharField(default='', max_length=250, verbose_name='Precios'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 15, 45, 45, 483548), verbose_name='Fecha'),
        ),
    ]
