# Generated by Django 3.1.2 on 2020-12-13 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0021_auto_20201212_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 22, 13, 23, 180359), verbose_name='Fecha'),
        ),
    ]
