# Generated by Django 3.1.2 on 2020-12-13 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0024_auto_20201212_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 22, 24, 40, 972482), verbose_name='Fecha'),
        ),
    ]
