# Generated by Django 3.1.2 on 2020-12-13 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVenta', '0027_auto_20201212_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 23, 35, 22, 624474), verbose_name='Fecha'),
        ),
    ]
