# Generated by Django 3.1.2 on 2020-12-13 06:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionVenta', '0028_auto_20201212_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 1, 52, 14, 603573), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionVenta.facturas'),
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_envio', models.CharField(default=0, max_length=10, verbose_name='Numero de envio')),
                ('status', models.CharField(default='', max_length=20, verbose_name='Estado')),
                ('sale', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionVenta.ventas')),
            ],
        ),
    ]
