# Generated by Django 3.1.2 on 2020-11-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
