# Generated by Django 3.1.2 on 2020-11-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0002_productos_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='img',
        ),
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/img/productos/', verbose_name='Imagen del Producto'),
        ),
    ]
