# Generated by Django 3.1.2 on 2020-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0004_auto_20201121_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/img/productos/', verbose_name='Imagen del Producto'),
        ),
    ]
