# Generated by Django 3.1.2 on 2020-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0005_auto_20201122_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/productos/', verbose_name='Imagen del Producto'),
        ),
    ]
