# Generated by Django 3.1.2 on 2020-12-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0006_auto_20201122_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='reference',
            field=models.IntegerField(max_length=10, null=True, unique=True, verbose_name='Numero de Referencia'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='enter_price',
            field=models.IntegerField(verbose_name='Precio de Entrada'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='exit_price',
            field=models.IntegerField(verbose_name='Precio de Salida'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='units',
            field=models.IntegerField(verbose_name='Unidades'),
        ),
    ]
