# Generated by Django 3.1.2 on 2020-12-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0007_auto_20201206_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('tlf', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='reference',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Numero de Referencia'),
        ),
        migrations.AddField(
            model_name='productos',
            name='provider',
            field=models.ForeignKey(default='Ninguno', on_delete=django.db.models.deletion.CASCADE, to='Almacen.proveedores'),
            preserve_default=False,
        ),
    ]
