# Generated by Django 3.1.2 on 2020-12-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0009_auto_20201207_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='provider',
        ),
    ]
