# Generated by Django 3.1.2 on 2020-12-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0010_remove_productos_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='provider',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Almacen.proveedores'),
        ),
    ]
