# Generated by Django 3.1.2 on 2020-12-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0012_productos_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='category',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='provider',
            new_name='Proveedor',
        ),
    ]
