# Generated by Django 3.1.2 on 2020-12-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0013_auto_20201207_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='name',
        ),
        migrations.RemoveField(
            model_name='proveedores',
            name='tlf',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='address',
            field=models.CharField(default='0', max_length=30, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='enterprise_name',
            field=models.CharField(default='0', max_length=30, verbose_name='Nombre de la empresa'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telephone',
            field=models.CharField(default='0', max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electronico'),
        ),
    ]
