# Generated by Django 3.1.2 on 2020-12-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0014_auto_20201207_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='address',
            field=models.CharField(default='', max_length=30, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='enterprise_name',
            field=models.CharField(default='', max_length=30, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telephone',
            field=models.CharField(default='', max_length=10, verbose_name='Telefono'),
        ),
    ]
