# Generated by Django 3.1.2 on 2020-12-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0015_auto_20201207_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='reference',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='reference',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Referencia'),
        ),
    ]
