# Generated by Django 3.1.2 on 2020-12-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0016_auto_20201208_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='address',
            field=models.CharField(default='', max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='enterprise_name',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telephone',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Telefono'),
        ),
    ]
